#mysql connection

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/personal_diary_app_db
#    username: root
#    password:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect


# h2 connection
spring:
  datasource:
    url: jdbc:h2:mem:personal_diary_app_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


server:
  port: 8080
